# Generated by Django 2.1.3 on 2018-11-18 16:28

from django.db import migrations, models
import utils.hshlib


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='hsh',
            field=models.CharField(db_index=True, default=utils.hshlib.get_hsh, max_length=128, unique=True),
        ),
    ]
