# Generated by Django 2.1.3 on 2018-11-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20181118_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='pages',
            field=models.IntegerField(default=0),
        ),
    ]
