# Generated by Django 2.1.3 on 2018-11-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_store_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='pages',
            field=models.IntegerField(default=None),
        ),
    ]
